import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
const pages = JSON.parse(readFileSync(new URL('../assets/legal/pages.json', import.meta.url)));
const escape = value => value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
for (const [name, translations] of Object.entries(pages)) {
  const directory = new URL(`../web/${name}/`, import.meta.url);
  mkdirSync(directory, { recursive: true });
  const sections = Object.entries(translations).map(([lang, paragraphs]) => `<section lang="${lang}"><h1>${escape(paragraphs[0])}</h1>${paragraphs.slice(1).map(p => `<p>${escape(p)}</p>`).join('')}</section>`).join('');
  const contact = `mailto:feedback@fiestaaa.app?subject=${encodeURIComponent(name === 'delete-account' ? 'Suppression de compte Fiestaaa' : 'Fiestaaa — Bêta')}`;
  writeFileSync(new URL('index.html', directory), `<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(translations.fr[0])} — Fiestaaa</title><style>@font-face{font-family:Manrope;src:url('/assets/assets/fonts/Manrope.ttf') format('truetype');font-display:swap}html{color-scheme:light dark}body{font:1rem/1.65 Manrope,system-ui,sans-serif;max-width:760px;margin:0 auto;padding:24px;color:#202132;background:#f8f8fc;overflow-wrap:anywhere}a{color:#6442df;text-underline-offset:.2em}a:focus-visible{outline:3px solid #6442df;outline-offset:4px}h1{font-size:1.75rem;line-height:1.25}section{margin:32px 0;padding:24px;border:1px solid #ddddea;border-radius:16px;background:#fff}nav{display:flex;gap:12px;flex-wrap:wrap}nav a{min-height:44px;display:inline-flex;align-items:center}@media(max-width:400px){body{padding:16px}section{padding:16px}}@media(prefers-color-scheme:dark){body{background:#151522;color:#eeeef6}section{background:#202030;border-color:#48485e}a{color:#b8aaff}a:focus-visible{outline-color:#b8aaff}}</style><nav><a href="/">Fiestaaa</a>${Object.keys(pages).map(p=>`<a href="/${p}">${escape(pages[p].fr[0])}</a>`).join('')}</nav>${sections}<p><a href="${contact}">feedback@fiestaaa.app</a></p></html>\n`);
}
